# theme: jekyll-theme-cayman

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-gist

# Pagination configuration (used by the `blog` layout)
paginate:              5
paginate_path:         /page-:num/